################################################################################
# Wiktor Adamski
# nr indeksu 272220
# Architektury systemów komputerowych - Lista 7 zadanie 9
################################################################################

all: prog.o
	gcc -Wall -Wextra prog.o -o prog

prog.o: prog.c
	gcc -Og -c -g prog.c

clean:
	rm -f prog.o prog
